version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=redis-user
      - REDIS_PASSWORD=redis-password
    networks:
      - otp-network
  otp-service:
    image: mohanadkhaled/otp-service:v1.0
    container_name: otp-service
    ports:
      - "8080:8080"
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge
