spring:
  application:
    name:
      otp-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      expiry-date: ${REDIS_EXPIRY_TIME_IN_MINS}
twilio:
    sid:
      ${API_KEY}
    auth-token:
      ${API_TOKEN}
    sender-number:
      ${SENDER_NUMBER}