repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Validates the syntax of YAML files.

  - repo: local
    hooks:
      - id: maven-validate # Runs Maven validate phase to trigger checkstyle plugin check code
        name: Maven Validate (Checkstyle)
        entry: mvn validate
        language: system
        pass_filenames: false # To avoid specific error of considering TwilioSenderService.java file as maven phase
#
#      - id: dependency-check # Scans the project for vulnerable dependencies.
#        name: Dependency Check
#        entry: mvn org.owasp:dependency-check-maven:check
#        language: system
#
#      - id: maven-test # Runs unit tests to ensure that your code changes don’t break any existing functionality.
#        name: Maven Test
#        entry: mvn test
#        language: system
